#!/bin/bash

# === HEADER ===
#FileName: bmtData
#Function: Contains Data utilities.
#library name: bashmultitool
#Written: Gavin Lyons
#URL: https://github.com/gavinlyonsrepo/BashMultiTool

# ===FUNCTIONS ===
function bmtDataFunc
{
	
case "$1" in

	intcheck) # 601 
		if [[ "$2" != *[!0-9]* ]];
			then
			#success an integer
			return 0
		fi
	;;

	alphanumcheck) #602
		if [[ "$2" != *[!0-9a-zA-Z]* ]];
			then
			#success an alpha numeric string
			return 0
		fi
	;;

	alphacheck) # 603
		if [[ "$2" != *[!a-zA-Z]* ]];
			then
			#success an alpha string
			return 0
		fi
	;;
	
	# 604
	lowercase) 
		echo "$2" | tr '[:upper:]' '[:lower:]' 
	;;
	
	# 605
	uppercase) 
		echo "$2" | tr '[:lower:]' '[:upper:]' 
	;;
	
	# 606
	trim) 
		: "${2#"${2%%[![:space:]]*}"}"
		: "${_%"${_##*[![:space:]]}"}"
		printf '%s\n' "$_"
	;;
	
	#607
	strlen) 
		[ -z "$2" ] && return 250
		return "$(printf "%s\\n" "${#2}")"
	;;

	*) # Catch all users typos
		printf '%s\n'  "Error: Unknown keyword : bashMultiTool: bmtData : bmtDataFunc"
		return 255
	;;
	
esac

return 2 # needed default
}

