#!/bin/bash

#=========================HEADER==========================================
#FileName: bmtData
#Function: Contains Data utilities.
#library name: bashmultitool
#Written: Gavin Lyons
#URL: https://github.com/gavinlyonsrepo/BashMultiTool

#====================FUNCTIONS===============================

function bmtDataFunc
{
	
case "$1" in

	intcheck) # 1 
		if [[ "$2" != *[!0-9]* ]];
			then
			#success an integer
			return 0
		fi
	;;

	alphanumcheck) #2
		if [[ "$2" != *[!0-9a-zA-Z]* ]];
			then
			#success an alpha numeric string
			return 0
		fi
	;;

	alphacheck) # 3
		if [[ "$2" != *[!a-zA-Z]* ]];
			then
			#success an alpha string
			return 0
		fi
	;;
	# 4 - 6 
	lowercase) echo "$2" | tr '[:upper:]' '[:lower:]' 
	return 0 ;;
	uppercase) echo "$2" | tr '[:lower:]' '[:upper:]' 
	return 0;;
	trim) echo "$2" 
	return 0;;
	
	
	*) # Catch all users typos
		printf '%s\n'  "Error: Unknown keyword : bashMultiTool: bmtData : bmtDataFunc"
		return 50
	;;
	
	
esac
return 2
}

