#!/bin/bash

# === HEADER ===
#FileName: bmtNetwork
#Function: Contains network related functions
#library name: bashmultitool
#URL: https://github.com/gavinlyonsrepo/BashMultiTool

# === FUNCTIONS ===

function bmtNetworkFunc
{
local	red
red=$(printf "\033[0;31m")
local	normal
normal=$(printf "\033[0m")

case "$1" in

	checknet) #  301 heck if website up
			#This uses netcat (nc) in its port scan mode,
			#a quick poke (-z is zero-I/O mode [used for
			#scanning]) with a quick timeout
			#(-w 1 waits at most one second
			#It checks passed website $1 on port 80 (HTTP).
		if nc -zw1 "$2" 80; then
			printf '%s\n' "We have connectivity $2"
			return 0
		else
			printf '%s\n' "${red}We do not have connectivity $2 ${normal}"
			return 2
		fi
	;;
	
	weather) 	# 302
		local mycityVar="$2"
		local myformat="$3"
		wget -qO - wttr.in/"$mycityVar"?format="$myformat"
		;;
	
	*) # Catch all users typos
		printf '%s\n'  "Error: Unknown keyword : bashMultiTool: bmtNetwork: bmtNetworkFunc"
		return 255
	;;
esac
}

