#!/bin/bash

#=========================HEADER==========================================
#FileName: bmtPrompt
#Function: Contains various screen prompts for user.  
#library name: bashmultitool
#Written: Gavin Lyons
#URL: https://github.com/gavinlyonsrepo/BashMultiTool

#====================FUNCTIONS===============================

function bmtPromptFunc
{
local	b_cyan=$(printf "\033[1;36m") 
local   red=$(printf "\033[0;31m")
local	normal=$(printf "\033[0m")
local	pacVar=""

case "$1" in 

	
	line) #1 print  cyan horizontal line of $2 i.e ======
		
		printf  "${b_cyan}%*s\n" "${COLUMNS:-$(tput cols)}" '' | tr ' ' "$2"
		printf '%s' "${normal}"
	;;
	
	anykey) #2 any key cyan prompt, appends second text input to prompt 
		printf '%s' "${b_cyan}" 
		read -n 1 -r -s -p "Press any key to continue $2"
		printf '%s\n' "${normal}"
	;;
	
	yesnoquit) #3 print yes no quit prompt [y/n/q]
		local	yellow=$(printf "\033[1;33m")
		local yesnoVar=""
		while true; do
			read -r yesnoVar
			case $yesnoVar in
				[Yy]*) return 0;;
				[Nn]*) return 2;;
				[Qq]*) return 3;;
				*) printf '%s\n' "${yellow}Please answer: (y/Y for yes) OR (n/N for no) OR (q/Q to quit)!${normal}";;
			esac
		done
	;;
	
	yesno) #4 print yes no prompt [y/N] or [Y/n] $2 determines option
		local yesnoVar=""
		local choiceVar=""
		
		if [ "$2" = yes ]; then
			choiceVar="yY"
		elif [ "$2" = no ]; then
			choiceVar="nN"
		else
			printf '%s\n'  "Error: Unknown Option to keyword yesno: bashmultitool, bmtPrompt, bmtPromptFunc"
			return 128
		fi
		 
		while true; do
			read -r yesnoVar
			case $yesnoVar in
				["$choiceVar"]*) return 0;;
				*) return 2;;
			esac
		done
	;;
	
	*) # Catch all users typos 
		printf '%s\n'  "Error: Unknown keyword : bashMultiTool: bmtPrompt : bmtPromptFunc"
		return 127
	;;
esac
}

