#!/bin/bash

#=========================HEADER==========================================
#FileName: bmtPrompt
#Function: Contains various screen prompts for user.  
#library name: bashmultitool
#Written: Gavin Lyons
#URL: https://github.com/gavinlyonsrepo/BashMultiTool

#====================FUNCTIONS===============================

function bmtPromptFunc
{
local	normal=$(printf "\033[0m")
local 	colorVar=""
if [ -n "$3" ]
then
	colorVar="$3"
else
	colorVar="b_cyan"
fi

case "$1" in 

	
	line) #1 print  cyan horizontal line of $2 i.e ======
		bmtPrintFunc "$colorVar"
		printf  "%*s\n" "${COLUMNS:-$(tput cols)}" '' | tr ' ' "$2"
		printf '%s' "${normal}"
	;;
	
	anykey) #2 any key cyan prompt, appends second text input to prompt 
		bmtPrintFunc "$colorVar"
		read -n 1 -r -s -p "Press any key to continue $2"
		printf '%s\n' "${normal}"
	;;
	
	yesnoquit) #3 print yes no quit prompt [y/n/q]
		local yesnoVar=""
		while true; do
			read -r yesnoVar
			case $yesnoVar in
				[Yy]*) return 0;;
				[Nn]*) return 2;;
				[Qq]*) return 3;;
				*) bmtPrintFunc b_yellow "Please answer: (y/Y for yes) OR (n/N for no) OR (q/Q to quit)!" ;;
			esac
		done
	;;
	
	yesno) #4 print yes no prompt [y/N] or [Y/n] $2 determines option
		local yesnoVar=""
		local choiceVar=""
		
		if [ "$2" = yes ]; then
			choiceVar="yY"
		elif [ "$2" = no ]; then
			choiceVar="nN"
		else
			bmtPrintFunc red "Error: Unknown Option to keyword yesno: bashmultitool, bmtPrompt, bmtPromptFunc"
			return 51
		fi
		 
		while true; do
			read -r yesnoVar
			case $yesnoVar in
				["$choiceVar"]*) return 0;;
				*) return 2;;
			esac
		done
	;;
	
	quitno) #5 print quit or no prompt [q/N] or [Q/n] $2 determines option
		local quitnoVar=""
		local choiceVar=""
		
		if [ "$2" = quit ]; then
			choiceVar="qQ"
		elif [ "$2" = no ]; then
			choiceVar="nN"
		else
			bmtPrintFunc red "Error: Unknown Option to keyword yesno: bashmultitool, bmtPrompt, bmtPromptFunc"
			return 51
		fi
		 
		while true; do
			read -r quitnoVar
			case $quitnoVar in
				["$choiceVar"]*) return 0;;
				*) return 2;;
			esac
		done
	;;
	
	*) # Catch all users typos 
		bmtPrintFunc red "Error: Unknown keyword : bashMultiTool: bmtPrompt : bmtPromptFunc"
		return 50
	;;
esac
}

