#!/bin/bash

#=========================HEADER==========================================
#FileName: bmtPrint
#Function: prints to screen 
#library name: bashmultitool
#Written: Gavin Lyons
#URL: https://github.com/gavinlyonsrepo/BashMultiTool

#====================FUNCTIONS===============================

# Name: function for printing text
# Process: Prints passed text "$2" in regular , bold , high intensity , underline , 
# background. "$1" is keyword. 8 colors 
function bmtPrintFunc
{
# Reset
local -r normal=$(printf "\033[0m")      # Text Reset

# Regular Colors
local -r black=$(printf "\033[0;30m")
local -r red=$(printf "\033[0;31m")
local -r green=$(printf "\033[0;32m")
local -r yellow=$(printf "\033[0;33m")
local -r blue=$(printf "\033[0;34m")
local -r purple=$(printf "\033[0;35m")
local -r cyan=$(printf "\033[0;36m")
local -r white=$(printf "\033[0;37m") 

# Bold
local -r b_black=$(printf "\033[1;30m")
local -r b_red=$(printf "\033[1;31m") 
local -r b_green=$(printf "\033[1;32m") 
local -r b_yellow=$(printf "\033[1;33m")
local -r b_blue=$(printf "\033[1;34m")
local -r b_purple=$(printf "\033[1;35m")
local -r b_cyan=$(printf "\033[1;36m")
local -r b_white=$(printf "\033[1;37m") 

# Underline
local -r u_black=$(printf "\033[4;30m")
local -r u_red=$(printf "\033[4;31m") 
local -r u_green=$(printf "\033[4;32m")
local -r u_yellow=$(printf "\033[4;33m")
local -r u_blue=$(printf "\033[4;34m") 
local -r u_purple=$(printf "\033[4;35m")
local -r u_cyan=$(printf "\033[4;36m")
local -r u_white=$(printf "\033[4;37m")

# Background
local -r bg_black=$(printf "\033[40m")
local -r bg_red=$(printf "\033[41m")
local -r bg_green=$(printf "\033[42m")
local -r bg_yellow=$(printf "\033[43m")
local -r bg_blue=$(printf "\033[44m")
local -r bg_purple=$(printf "\033[45m")
local -r bg_cyan=$(printf "\033[46m")
local -r bg_white=$(printf "\033[47m")

# High Intensity
local -r i_black=$(printf "\033[0;90m")
local -r i_red=$(printf "\033[0;91m")
local -r i_green=$(printf "\033[0;92m")
local -r i_yellow=$(printf "\033[0;93m")
local -r i_blue=$(printf "\033[0;94m")
local -r i_purple=$(printf "\033[0;95m")
local -r i_cyan=$(printf "\033[0;96m")
local -r i_white=$(printf "\033[0;97m")

case "$1" in 

	#print passed text string, reset
	norm) printf '%s\n' "${normal}$2" ;;
	
	#reg
	black) printf '%s\n' "${black}$2${normal}" ;;
	red) printf '%s\n' "${red}$2${normal}" ;;
	green) printf '%s\n' "${green}$2${normal}" ;;
	yellow)printf '%s\n' "${yellow}$2${normal}" ;;
	blue) printf '%s\n' "${blue}$2${normal}" ;;
	purple)printf '%s\n' "${purple}$2${normal}" ;;
	cyan) printf '%s\n' "${cyan}$2${normal}" ;;
	white) printf '%s\n' "${white}$2${normal}" ;;
	
	#bold
	b_black) printf '%s\n' "${b_black}$2${normal}" ;;
	b_red) printf '%s\n' "${b_red}$2${normal}" ;;
	b_green) printf '%s\n' "${b_green}$2${normal}" ;;
	b_yellow)printf '%s\n' "${b_yellow}$2${normal}" ;;
	b_blue) printf '%s\n' "${b_blue}$2${normal}" ;;
	b_purple)printf '%s\n' "${b_purple}$2${normal}" ;;
	b_cyan) printf '%s\n' "${b_cyan}$2${normal}" ;;
	b_white) printf '%s\n' "${b_white}$2${normal}" ;;
	
	#underline
	u_black) printf '%s\n' "${u_black}$2${normal}" ;;
	u_red) printf '%s\n' "${u_red}$2${normal}" ;;
	u_green) printf '%s\n' "${u_green}$2${normal}" ;;
	u_yellow)printf '%s\n' "${u_yellow}$2${normal}" ;;
	u_blue) printf '%s\n' "${u_blue}$2${normal}" ;;
	u_purple)printf '%s\n' "${u_purple}$2${normal}" ;;
	u_cyan) printf '%s\n' "${u_cyan}$2${normal}" ;;
	u_white) printf '%s\n' "${u_white}$2${normal}" ;;
	
	#background
	bg_black) printf '%s\n' "${bg_black}$2${normal}" ;;
	bg_red) printf '%s\n' "${bg_red}$2${normal}" ;;
	bg_green) printf '%s\n' "${bg_green}$2${normal}" ;;
	bg_yellow)printf '%s\n' "${bg_yellow}$2${normal}" ;;
	bg_blue) printf '%s\n' "${bg_blue}$2${normal}" ;;
	bg_purple)printf '%s\n' "${bg_purple}$2${normal}" ;;
	bg_cyan) printf '%s\n' "${bg_cyan}$2${normal}" ;;
	bg_white) printf '%s\n' "${bg_white}$2${normal}" ;;
	
	# High Intensity
	i_black) printf '%s\n' "${i_black}$2${normal}" ;;
	i_red) printf '%s\n' "${i_red}$2${normal}" ;;
	i_green) printf '%s\n' "${i_green}$2${normal}" ;;
	i_yellow)printf '%s\n' "${i_yellow}$2${normal}" ;;
	i_blue) printf '%s\n' "${i_blue}$2${normal}" ;;
	i_purple)printf '%s\n' "${i_purple}$2${normal}" ;;
	i_cyan) printf '%s\n' "${i_cyan}$2${normal}" ;;
	i_white) printf '%s\n' "${i_white}$2${normal}" ;;
	
	
	*) # Catch all user typos 
		printf '%s\n'  "Error: Unknown keyword : bahsmultitool: bmtPrint: bmtPrintFunc"
		return 127
	;;
esac
}


